package FrontEnd;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import skill.forge.*;


public class LessonList extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LessonList.class.getName());
    private Course course;
    private String courseId;
    private Student student;
    private LessonService lessonService;
    private CourseService courseService;
    private JsonDataBaseManager dbManager;

    /**
     * Creates new form NewJFrame
     */
    public LessonList(Course course, Student student, JsonDataBaseManager dbManager) {
        initComponents();
        this.courseId = courseId;
        this.course = course;
        this.student = student;
        this.dbManager = dbManager;

        jLabel1.setText(course.getTitle() + " :" + "Lessons ");
        courseService = new CourseService(dbManager);
        lessonService = new LessonService(dbManager);
        loadintoTable(this.course);
    }

    private void loadintoTable(Course course) {
        String courseId = course.getCourseId();

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            List<Lesson> lessons = new ArrayList<>();
            lessons = lessonService.getlessonsByCourse(courseId);
            System.out.println("Loading lessons for courseId = " + courseId);
            System.out.println("Found lessons: " + lessons.size());

            for (Lesson lesson : lessons) {
                // Check if lesson has quiz
                boolean hasQuiz = lesson.hasQuiz();
                String quizStatus = hasQuiz ? "Has Quiz" : "No Quiz";

                // Check if student has completed this lesson
                boolean isCompleted = isLessonCompleted(lesson.getLessonId());
                String completionStatus = isCompleted ? "✓ Completed" : "Not Started";

                model.addRow(new Object[]{
                    lesson.getLessonId(),
                    lesson.getTitle(),
                    quizStatus,
                    completionStatus
                });
            }

            if (lessons.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No lessons found for this course.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading lessons: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private boolean isLessonCompleted(String lessonId) {
        // Check if this lesson is in student's completed lessons
        List<String> completedLessons = student.getCompletedLessons(course.getCourseId());
        return completedLessons != null && completedLessons.contains(lessonId);
    }

    public void refreshLessonList() {
        loadintoTable(course);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jlabel1");

        jButton1.setText("View Lesson");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back to StudentDashboard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {

            },
            new String [] {
                "LessonID", "Title", "Quiz", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

        }
    );
    jTable1.setEnabled(true);
    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane2.setViewportView(jTable1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jButton2)
                    .addGap(242, 242, 242)
                    .addComponent(jButton1))
                .addGroup(layout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(11, 11, 11))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton2)
                .addComponent(jButton1)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: view lesson button
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            // Get lesson ID from the selected row (column 0)
            String lessonId = jTable1.getValueAt(selectedRow, 0).toString();
            String lessonTitle = jTable1.getValueAt(selectedRow, 1).toString();

            System.out.println("Button action on selected row - Lesson ID: " + lessonId + ", Title: " + lessonTitle);

            // Use the service method to get the lesson
            Lesson selectedLesson = lessonService.getLessonById(course.getCourseId(), lessonId);

            if (selectedLesson != null) {
                // Open the lesson viewer with the selected lesson
                LessonViewerFrame lessonViewer = new LessonViewerFrame(student, course, selectedLesson,dbManager);
                lessonViewer.setVisible(true);

                // Optional: Add listener to refresh when lesson viewer closes
                lessonViewer.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent e) {
                        // Refresh the table to show updated completion status
                        loadintoTable(course);
                    }
                });
            } else {
                JOptionPane.showMessageDialog(this, "Error: Could not load lesson details.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a lesson to view.");
            System.out.println("No row selected.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // new StudentDashboardFrame((java.awt.Frame) null, true, student, dbManager).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

            /**
             * @param args the command line arguments
             */
            public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                    logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                //java.awt.EventQueue.invokeLater(() -> new LessonList().setVisible(true));
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        // Minimal test course

                        //new LessonList(courseService.getcourseById).setVisible(true); //totally invalid line it needs to be called from somewhere else
//            Course courseee = new Course("C101","Java Basics","Introduction to java Programminggg","I100");
                    }
                });

            }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

